### ISSUE TITLE
Self Service: User Management

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#33]
**Goal:**

As a user,
I want a screen to view all the clients (self-service/non-self-service users)
so that I can manage them as a whole.

**Tasks:**    
  1.  Add a screen to manage all clients (self-service/non-self-service users)
  2.  Add feature to search
  3.  Allow bulk activation/deactivation of self-service users
  4.  Add feature for creating a self-service user
  5. Click and view details of a client (self-service/non-self-service users)
  6. Edit details of a client (self-service/non-self-service users)

**Acceptance Criteria:**
  - [x]  Add a screen to manage all clients (self-service/non-self-service users)
  - [x]  Add feature to search
  - [ ]  Allow bulk activation/deactivation of self-service users
  - [x]  Add feature for creating a self-service user
  - [x]  Click and view details of a client (self-service/non-self-service users)
  - [x]  Edit details of a client (self-service/non-self-service users)

**UPDATE:** User Interface completed. Functionality can be completed once required APIs are available.

Fineract: https://issues.apache.org/jira/browse/FINERACT-638

**Comment by abhaychawla** [comment]
##Mockups for reference:

![3 user management 1](https://user-images.githubusercontent.com/16948598/41100116-18edb792-6a7e-11e8-811e-cb8cec705458.png)
![4 user management 2](https://user-images.githubusercontent.com/16948598/41100117-19625818-6a7e-11e8-8048-e42b2059e99f.png)
![5 user management 3](https://user-images.githubusercontent.com/16948598/41100114-1867e9aa-6a7e-11e8-8128-cf0bd6caecdf.png)

**Comment by abhaychawla** [comment]
@edcable @gauravsaini03 @anweshknayak 
Should we add the requirements for the self-service user management in the current clients' page itself or create it as a separate component for now?

**Comment by anweshknayak** [comment]
I think @gauravsaini03 mentioned to keep it separate.

**Comment by abhaychawla** [comment]
Okay.

**Comment by anweshknayak** [comment]
Also one more thing. We already using bootswatch for the material look, which is overriding the default bootstrap.css with the bootswatch one. So using material-angular will just increase the overhead and make it more slow. 
Also bootstrap.js doesn't work in angular for that there's https://ng-bootstrap.github.io/#/components/accordion/examples. I am using this for now. As it is lightweight and replacement for bootstrap.js.

For now we should stick to

- bootswatch
- ng-bootstrap

using material-angular doesn't make sense as we already have the material view. Let me know what you think about it. We can use if there is a dire need and it doesn't get solved without the above two mentioned. Also it's better if we use external libraries to a minimal extent for optimal performance of site.

**Comment by abhaychawla** [comment]
Yes, I agree with you. We should stick to using bootswatch. I was also thinking about why we might need to use both. Could you please confirm once you are using ng-bootstrap or ngx-bootstrap? @anweshknayak

**Comment by abhaychawla** [comment]
As per community discussion, we shifted to using angular-material.
