### ISSUE TITLE
Web-App Configuration

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#35]
**Goal:**

As a user,
I want to configure the look and feel of the application
so that it suits the needs of the organization.

**Tasks:**    
  1.  Add settings for web-app configuration
  2.  Allow configuration of the name of the organization, its description, a summary, default language and date format to be used within the application.
  3.  Allow configuration of favicon and logo of the organization.
  4.  Allow configuration of the theme and fonts for the application.
  5.  Allow configuration of the contact information of the organization (website, email, phone)

**Acceptance Criteria:**
  - [x]  Add settings for web-app configuration
  - [ ]  Allow configuration of the name of the organization, its description, a summary, default language and date format to be used within the application.
  - [ ]  Allow configuration of favicon and logo of the organization.
  - [x]  Allow configuration of the theme for the application.
  - [ ]  Allow configuration of the fonts for the application.
  - [ ]  Allow configuration of the contact information of the organization (website, email, phone)

**UPDATE:** User Interface completed. Functionality can be completed once required APIs are available.

Fineract: https://issues.apache.org/jira/browse/FINERACT-638

**Comment by abhaychawla** [comment]
**Mockups for reference:**

![13 app configuration app](https://user-images.githubusercontent.com/16948598/41101249-48c7aca4-6a81-11e8-9800-38a1e19e1fd7.png)
![14 app configuration app 1](https://user-images.githubusercontent.com/16948598/41101250-490bfa08-6a81-11e8-8d9a-0ab818de6b77.png)
![15 app configuration app 2](https://user-images.githubusercontent.com/16948598/41101254-495d6dca-6a81-11e8-9fc4-e8da52fa2510.png)
![16 app configuration app 3](https://user-images.githubusercontent.com/16948598/41101255-4a3324e2-6a81-11e8-802e-336f9ba42cd7.png)
![17 app configuration app 4](https://user-images.githubusercontent.com/16948598/41101248-482d3c5a-6a81-11e8-95ea-837838b49bbc.png)

**Comment by abhaychawla** [comment]
@anweshknayak 
I have created a demo here: https://abhaychawla.github.io/angular-theme/
Its a simple example to show how we can allow customization of the theme using bootstrap at client's side using local storage. I have used the loader that you created as a trial so that we could incorporate that as well whenever the theme is configured during the initial load. Further this data could be stored on the server when the required API is created.
How does it look to you?
I will integrate this into the web-app so that we can use the themes from bootswatch and angular-material.

**Comment by abhaychawla** [comment]
Yes, I'll take his review as well. We can provide as many themes as required by default and if needed we can provide instructions so that the organization will be able to clone the project, create their own custom theme and build it according to their needs as well.
