### ISSUE TITLE
Online Banking App and Android App Configuration

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#36]
**Goal:**

As a user,
I want to configure the look and feel of online banking app and android app
so that it suits the needs of the organization and the self-service users.  

**Tasks:**    
  1.  Add settings for online banking app and android app configuration
  2.  Allow configuration of the name of the organization, its description, a summary, default language and date format to be used within the application.
  3.  Allow configuration of favicon and logo of the organization. (where required)
  4.  Allow configuration of the theme and fonts for the application.
  5.  Allow configuration of the contact information of the organization (website, email, phone)

 
**Acceptance Criteria:**
  - [x]  Add settings for online banking app and android app configuration
  - [ ]  Allow configuration of the name of the organization, its description, a summary, default language and date format to be used within the application.
  - [ ]  Allow configuration of favicon and logo of the organization. (where required)
  - [ ]  Allow configuration of the theme and fonts for the application.
  - [ ]  Allow configuration of the contact information of the organization (website, email, phone)

**UPDATE:** User Interface completed. Functionality can be completed once required APIs are available.

Fineract: https://issues.apache.org/jira/browse/FINERACT-638

**Comment by abhaychawla** [comment]
Please refer to issue #35 for similar mockups. For this issue, I require the details about the theme configuration and any other requirements apart from the ones mentioned here, for both the applications.
